spring:
  profiles:
    active: dev
  freemarker:
    template-loader-path: 'classpath:/templates'

---
spring:
  config:
    activate:
      on-profile: dev
  mail:
    host: 'sandbox.smtp.mailtrap.io'
    port: 587
    username: 876d18191cae1c
    password: 75483af4e1a8fd
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/airline_reservation
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/airline_reservation
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true